-- Enable PostGIS extension (Supabase usually has this enabled by default, but good to include)
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. PROFILES (Linked to Supabase Auth)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  role TEXT CHECK (role IN ('admin', 'driver', 'municipal_manager')),
  wilaya_code TEXT,
  phone_number TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ROAD NETWORK (From routing/schema.sql)
CREATE TABLE road_nodes (
    id BIGINT PRIMARY KEY,
    osmid BIGINT,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    geom GEOMETRY(Point, 4326)
);
CREATE INDEX idx_road_nodes_geom ON road_nodes USING GIST(geom);

CREATE TABLE road_edges (
    u BIGINT REFERENCES road_nodes(id),
    v BIGINT REFERENCES road_nodes(id),
    key INT,
    osmid BIGINT[],
    name TEXT,
    highway TEXT,
    oneway BOOLEAN,
    length DOUBLE PRECISION,
    speed_kph DOUBLE PRECISION,
    travel_time DOUBLE PRECISION,
    geom GEOMETRY(LineString, 4326),
    PRIMARY KEY (u, v, key)
);
CREATE INDEX idx_road_edges_geom ON road_edges USING GIST(geom);

-- 3. ADMINISTRATIVE ZONES
CREATE TABLE admin_zones (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    admin_level INT,
    wilaya_code TEXT,
    commune_code TEXT,
    geom GEOMETRY(MultiPolygon, 4326)
);
CREATE INDEX idx_admin_zones_geom ON admin_zones USING GIST(geom);

-- 4. WASTE MANAGEMENT ASSETS
CREATE TABLE waste_points (
    id SERIAL PRIMARY KEY,
    location_name TEXT,
    capacity DOUBLE PRECISION,
    current_fill_level DOUBLE PRECISION DEFAULT 0,
    waste_type TEXT,
    geom GEOMETRY(Point, 4326),
    closest_node_id BIGINT REFERENCES road_nodes(id)
);
CREATE INDEX idx_waste_points_geom ON waste_points USING GIST(geom);

CREATE TABLE trucks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    plate_number TEXT UNIQUE,
    model TEXT,
    capacity_tons DOUBLE PRECISION,
    driver_id UUID REFERENCES profiles(id),
    current_status TEXT DEFAULT 'idle', -- idle, on_route, maintenance
    last_location GEOMETRY(Point, 4326),
    last_updated TIMESTAMPTZ
);

-- 5. OPERATIONS & TRACKING
CREATE TABLE tracking_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id UUID REFERENCES trucks(id),
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    speed DOUBLE PRECISION,
    heading DOUBLE PRECISION,
    geom GEOMETRY(Point, 4326)
);
CREATE INDEX idx_tracking_history_truck ON tracking_history(truck_id);
CREATE INDEX idx_tracking_history_time ON tracking_history(timestamp);

CREATE TABLE collection_tasks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    truck_id UUID REFERENCES trucks(id),
    status TEXT DEFAULT 'pending', -- pending, in_progress, completed, skipped
    assigned_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    waste_point_id INT REFERENCES waste_points(id),
    collected_weight DOUBLE PRECISION,
    manifest_notes TEXT
);

-- 6. ISSUES & REPORTING
CREATE TABLE waste_issues (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    reporter_id UUID REFERENCES profiles(id),
    issue_type TEXT, -- overflow, broken_bin, illegal_dumping
    description TEXT,
    status TEXT DEFAULT 'open', -- open, assigned, resolved
    geom GEOMETRY(Point, 4326),
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. ANALYTICS (Metric Snapshots)
CREATE TABLE municipal_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wilaya_code TEXT,
    date DATE DEFAULT CURRENT_DATE,
    collection_coverage DOUBLE PRECISION,
    landfill_diversion_rate DOUBLE PRECISION,
    cost_recovery_rate DOUBLE PRECISION,
    circular_economy_value DOUBLE PRECISION,
    wpi_score DOUBLE PRECISION, -- Waste Pressure Index
    zpi_score DOUBLE PRECISION, -- Zone Performance Index
    UNIQUE(wilaya_code, date)
);

-- ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

ALTER TABLE waste_issues ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can read issues" ON waste_issues FOR SELECT USING (true);
CREATE POLICY "Authenticated users can report issues" ON waste_issues FOR INSERT WITH CHECK (auth.role() = 'authenticated');
